trigger:
- dev
- master

pool:
  name: ubuntu-18.04
  demands: java

steps:
- task: GitVersion@5
  displayName: GitVersion
  inputs:
    preferBundledVersion: false
    configFilePath: 'GitVersion.yml'
    updateAssemblyInfo: false
  enabled: true

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.Repository.LocalPath)/build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/WebApp.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/WebApp.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'